name: Test and Upload artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Build and package project
        run: mvn install
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of a target directory
        run: ls -la target
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./target/backend-0.0.1-SNAPSHOT.jar